# Google Cloud Build configuration for Pinthenews
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/pinthenews:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/pinthenews:latest',
      '.'
    ]
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pinthenews:$COMMIT_SHA']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pinthenews:latest']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'pinthenews',
      '--image', 'gcr.io/$PROJECT_ID/pinthenews:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '2Gi',
      '--cpu', '2',
      '--port', '8080',
      '--set-env-vars', 'PORT=8080',
      '--max-instances', '10',
      '--timeout', '900',
      '--concurrency', '100'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
  
images:
  - 'gcr.io/$PROJECT_ID/pinthenews:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/pinthenews:latest'

timeout: 1800s