# Cloud Run service configuration for Pinthenews
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pinthenews
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        # CPU and memory allocation
        run.googleapis.com/cpu: "2"
        run.googleapis.com/memory: "2Gi"
        
        # Scaling configuration
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        
        # Timeout configuration  
        run.googleapis.com/timeout: "900s"
        
        # Other optimizations
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
        
    spec:
      # Maximum concurrent requests per instance
      containerConcurrency: 100
      
      containers:
      - image: gcr.io/PROJECT_ID/pinthenews:latest
        
        # Port configuration
        ports:
        - containerPort: 8080
          name: http1
          
        # Environment variables
        env:
        - name: PORT
          value: "8080"
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: anthropic-api-key
              key: key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: key
              
        # Resource limits
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 1Gi
            
        # Health check configuration
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 30
          
        startupProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10